default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
exclude: |
  (?x)(
      ^public/|
      ^resources/_gen/
  )

# - repo: https://github.com/jumanjihouse/pre-commit-hooks
#   rev: master
#   hooks:
#     - id: markdownlint
